server:
  port: 8081

spring:

  data:
    jpa:
      repositories:
        enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/track_tagger
    username: root
    password: 1234

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    enabled: true
    prefix: file:src/main/resources/templates/
    suffix: .html
    cache: false

  resources:
    static-locations: file:src/main/resources/static/
    cache:
      period: 0


